### ISSUE TITLE
missing words

### ISSUE THREAD

**Issue by lsmith77** [gambolputty/german-nouns#8]
I stumbled over some missing words and can imagine more need to be added like `Schwachpunkt` and `Erschwernis`. 

I guess such missing words need to be added to Wiktionary as per https://github.com/gambolputty/german-nouns#2-compile-the-list-of-nouns-from-a-wiktionary-xml-file ?

**Comment by gambolputty** [comment]
Yes! They don't exist yet in the Wiktionary (even though they seem pretty common to me). This package only parses what's available inside the XML files, so they would need to be added to the German Wiktionary first.

**Comment by lsmith77** [comment]
ok thank you for confirming.
